-- Generated by scripts/silver_generate.py from contracts/corebank/card_product_classes.yml; do not edit.
{{ scd2(ref('br_corebank__card_product_classes'), ['card_product_class_id'], deleted='false') }}
