-- Generated by scripts/silver_generate.py from contracts/corebank/interchange_rates.yml; do not edit.
select
    *,
    valid_from_date as _business_valid_from_date,
    {{ business_valid_to('valid_to_date') }} as _business_valid_to_date
from (
    {{ scd2(ref('br_corebank__interchange_rates'), ['interchange_rate_id'], deleted='false') }}
)
