-- Generated by scripts/silver_generate.py from contracts/corebank/loan_application_statuses.yml; do not edit.
{{ scd2(ref('br_corebank__loan_application_statuses'), ['loan_application_status_id'], deleted='false') }}
