-- Generated by scripts/silver_generate.py from contracts/corebank/transaction_statuses.yml; do not edit.
{{ scd2(ref('br_corebank__transaction_statuses'), ['transaction_status_id'], deleted='false') }}
