{#
  The generic tests silver models carry (specification 008 sections 1, 2 and 10). Each is
  declared with severity `error` in the model's properties, generated by
  `scripts/silver_generate.py` for the models that mirror a contract entity, and `make dbt-prove`
  shows each failing on a planted fixture.

  A failing row names keys and instants, never a value an identifier, quasi-identifier or
  sensitive column holds, and `store_failures` is never set (`bronze_guard`).
#}

{# The declared grain: no two rows share it. #}
{% test silver_unique_key(model, columns) %}
select {{ columns | join(', ') }}, count(*) as occurrences
  from {{ model }}
 group by {{ columns | join(', ') }}
having count(*) > 1
{% endtest %}

{# No null in any column of the grain. #}
{% test silver_not_null(model, columns) %}
select {{ columns | join(', ') }}
  from {{ model }}
 where {% for column in columns -%}
       "{{ column }}" is null{% if not loop.last %} or {% endif %}
       {%- endfor %}
{% endtest %}

{#
  A minimum cardinality, stated as a number where the test is declared and never read from the
  thing under test: a model that builds empty passes every other test.
#}
{% test silver_min_rows(model, minimum) %}
select count(*) as held, {{ minimum }} as minimum
  from {{ model }}
having count(*) < {{ minimum }}
{% endtest %}

{#
  The versions of each key tile time from the epoch with no gap and no overlap: the first opens
  at the epoch, each later one at the instant the one before it closed, every interval is
  non-empty, and only the last may be current, which it is exactly when it closes at the end of
  time. A key whose last version closed by a soft delete has no current version and passes.

  A restoration after a soft delete would leave a gap, and this test fails on it: planning
  measured none, and the first one is a decision to take rather than a shape to accept.
#}
{% test silver_scd2_intervals(model, key) %}
{%- set k = key | join(', ') -%}
with ordered as (
    select {{ k }}, _valid_from, _valid_to, _is_current,
           lag(_valid_to) over w as _previous_to,
           lead(_valid_from) over w as _next_from,
           row_number() over w as _version
      from {{ model }}
    window w as (partition by {{ k }} order by _valid_from)
),

judged as (
    select {{ k }}, _valid_from,
           case
               when _valid_from >= _valid_to then 'an empty or inverted interval'
               when _version = 1 and _valid_from <> {{ scd2_epoch() }}
                   then 'the first version does not open at the epoch'
               when _version > 1 and _valid_from <> _previous_to
                   then 'a gap or an overlap with the version before'
               when _is_current <> (_valid_to = {{ scd2_end() }})
                   then 'the current flag disagrees with the closing instant'
               when _is_current and _next_from is not null
                   then 'a current version that is not the last'
           end as problem
      from ordered
)

select * from judged where problem is not null
{% endtest %}

{#
  Re-reads agree (criterion 2): the bronze rows sharing a key and `updated_at` are one version
  read by more than one batch, and must hold the same value in every contract column. Silver
  keeps the earliest batch's, which is only safe while this holds. The platform's audit columns,
  which start with an underscore, are what differs between re-reads by design.
#}
{% test silver_rereads_agree(model, upstream, key) %}
{%- set columns = [] -%}
{%- if execute -%}
  {%- for column in adapter.get_columns_in_relation(upstream) -%}
    {%- if not column.name.startswith('_') -%}
      {%- do columns.append('"' ~ column.name ~ '"') -%}
    {%- endif -%}
  {%- endfor -%}
{%- endif -%}
{%- if columns | length == 0 -%}
  {%- do columns.append('updated_at') -%}
{%- endif -%}
select {{ key | join(', ') }}, updated_at, count(distinct row({{ columns | join(', ') }})) as states
  from {{ upstream }}
 group by {{ key | join(', ') }}, updated_at
having count(distinct row({{ columns | join(', ') }})) > 1
{% endtest %}

{#
  Every observation is a version (criterion 3), for an SCD2 model with no excluded measure:
  each observation of the upstream that is not a soft delete opens one, whether or not a contract
  column changed, because a new `updated_at` with nothing visible changed is a source update the
  contract does not describe (the merchants case). Returns the observations with no version
  opening at them; a key's first opens at the epoch.
#}
{% test silver_observations_versioned(model, upstream, key, deleted='is_deleted') %}
{%- set k = key | join(', ') -%}
with observed as (
    select distinct on ({{ k }}, updated_at) {{ k }}, updated_at, ({{ deleted }}) as _deleted
      from {{ upstream }}
     order by {{ k }}, updated_at, _batch_id
),

expected as (
    select {{ k }},
           case when row_number() over (partition by {{ k }} order by updated_at) = 1
                then {{ scd2_epoch() }} else updated_at end as _valid_from
      from observed
     where not _deleted
)

select {{ k }}, _valid_from from expected
except
select {{ k }}, _valid_from from {{ model }}
{% endtest %}

{#
  A fact resolves to exactly one version (criterion 4): for every row with a value in
  `column_name`, the versions of `to` whose `to_column` holds it and whose interval contains the
  fact's instant `at` number exactly one. None is a fact before its entity existed or after it
  was deleted; two is an overlap. Returns the value and the count, never the fact's other
  columns.
#}
{% test silver_resolves_one_version(model, column_name, to, to_column, at) %}
with facts as (
    select row_number() over () as fact_row, "{{ column_name }}" as value, {{ at }} as fact_at
      from {{ model }}
     where "{{ column_name }}" is not null
),

{#- Counted per fact: two facts with one value at one instant are two facts, not two versions. #}
resolved as (
    select f.fact_row, f.value, f.fact_at, count(v."{{ to_column }}") as versions
      from facts f
      left join {{ to }} v
        on v."{{ to_column }}" = f.value
       and v._valid_from <= f.fact_at
       and f.fact_at < v._valid_to
     group by f.fact_row, f.value, f.fact_at
)

select value, min(fact_at) as first_at, count(*) as facts, min(versions) as fewest,
       max(versions) as most
  from resolved
 where versions <> 1
 group by value
{% endtest %}

{#
  A converted amount carries its provenance (criteria 11 and 12, `conventions.md`): EUR at a rate
  of 1 with no rate date and the amount unchanged; a missing rate with a null amount, never zero
  and never the original; every other row with its amount, rate and rate date; and only a
  converted non-EUR row ever provisional or carried. Returns the offending rows' keys.
#}
{% test silver_fx_provenance(model, key, amount, currency) %}
{%- set eur = amount ~ '_eur' -%}
select {{ key }}, {{ currency }}, fx_is_missing, fx_is_provisional
  from {{ model }}
 where fx_is_missing is null or fx_is_carried is null or fx_is_provisional is null
    or ({{ currency }} = 'EUR' and (fx_rate <> 1 or fx_rate_date is not null
                                    or {{ eur }} is distinct from {{ amount }}
                                    or fx_is_missing or fx_is_carried or fx_is_provisional))
    or ({{ currency }} <> 'EUR' and fx_is_missing
        and ({{ eur }} is not null or fx_rate is not null or fx_rate_date is not null
             or fx_is_carried or fx_is_provisional))
    or ({{ currency }} <> 'EUR' and not fx_is_missing
        and ({{ eur }} is null or fx_rate is null or fx_rate_date is null))
{% endtest %}
