"""The silver models that mirror an entity are generated from the contracts, and checked."""

import shutil
from pathlib import Path

import dbt_generate
import pytest
import silver_generate

ROOT = Path(__file__).resolve().parents[2]
# Twenty-nine `ref` tables and `agent_locations` at this commit. Stated, never read from the
# thing under test.
GENERATED_SQL = 30
REFERENCE_TABLES = 29


@pytest.fixture
def workspace(tmp_path, monkeypatch):
    """Copies of the contracts, the silver models and the inventory the generator can edit."""
    contracts = tmp_path / "contracts"
    models = tmp_path / "silver"
    shutil.copytree(ROOT / "contracts", contracts)
    shutil.copytree(ROOT / "dbt" / "models" / "silver", models)
    inventory = tmp_path / "model_inventory.md"
    shutil.copy(ROOT / "docs" / "model_inventory.md", inventory)
    monkeypatch.setattr(dbt_generate, "CONTRACTS", contracts)
    monkeypatch.setattr(silver_generate, "MODELS", models)
    monkeypatch.setattr(silver_generate, "INVENTORY", inventory)
    return tmp_path


def test_every_ref_table_and_agent_locations_has_a_generated_model():
    models = silver_generate.build()
    generated = [m for m in models if m.spec.generated]
    assert len(generated) == GENERATED_SQL
    references = [m for m in generated if m.bronze.current.source_schema == "ref"]
    assert len(references) == REFERENCE_TABLES
    committed = sorted(p.stem for p in (ROOT / "dbt" / "models" / "silver").glob("sl_*.sql"))
    assert set(m.name for m in generated) <= set(committed)


def test_the_committed_files_agree_with_the_contracts():
    assert silver_generate.main(["--check"]) == 0


def test_a_hand_edit_to_a_generated_model_fails_the_check(workspace):
    target = workspace / "silver" / "sl_currencies.sql"
    target.write_text(target.read_text(encoding="utf-8").replace("'false'", "'true'"))
    assert silver_generate.main(["--check"]) == 1


def test_a_hand_edit_to_generated_properties_fails_the_check(workspace):
    target = workspace / "silver" / "sl_currencies.yml"
    target.write_text(target.read_text(encoding="utf-8").replace("minimum: 9", "minimum: 1"))
    assert silver_generate.main(["--check"]) == 1


def test_a_contract_changed_without_regenerating_fails_the_check(workspace):
    contract = workspace / "contracts" / "corebank" / "currencies.yml"
    text = contract.read_text(encoding="utf-8")
    contract.write_text(
        text.replace("classification: non-personal", "classification: sensitive", 1)
    )
    assert silver_generate.main(["--check"]) == 1
    assert silver_generate.main([]) == 0
    assert silver_generate.main(["--check"]) == 0


def test_a_stray_generated_file_fails_the_check(workspace):
    (workspace / "silver" / "sl_nothing.sql").write_text(
        "-- Generated by scripts/silver_generate.py from nowhere; do not edit.\nselect 1\n"
    )
    assert silver_generate.main(["--check"]) == 1


def test_ref_models_retain_inactive_rows_and_core_models_apply_deletes():
    models = {m.name: m for m in silver_generate.build()}
    for model in models.values():
        sql = silver_generate.render_sql(model) if model.spec.generated else ""
        if model.bronze.current.source_schema == "ref":
            assert "deleted='false'" in sql, model.name
            assert any(c.name == "is_active" for c in model.columns), model.name
        elif model.spec.generated:
            assert "deleted=" not in sql, model.name
    assert not any(c.name == "is_deleted" for m in models.values() for c in m.columns)


def test_a_ref_table_without_a_floor_fails_generation(monkeypatch):
    floors = dict(silver_generate.REFERENCE_FLOORS)
    del floors["currencies"]
    monkeypatch.setattr(silver_generate, "REFERENCE_FLOORS", floors)
    with pytest.raises(SystemExit):
        silver_generate.build()


def test_every_model_tests_its_grain_floor_rereads_and_intervals():
    for model in silver_generate.build():
        text = silver_generate.render_yml(model)
        for test in ("silver_unique_key", "silver_not_null", "silver_min_rows"):
            assert test in text, (model.name, test)
        assert f"upstream: ref('{model.bronze.name}')" in text
        scd2 = model.spec.history == silver_generate.SCD2
        assert ("silver_scd2_intervals" in text) == scd2
        assert ("silver_observations_versioned" in text) == (scd2 and not model.spec.excluded)
        assert "store_failures" not in text


def test_classifications_are_carried_from_bronze():
    bronze = {m.entity: m for m in dbt_generate.build_models() if m.source_system == "corebank"}
    for model in silver_generate.build():
        carried = {c.name: c.classification for c in bronze[model.spec.entity].columns}
        for column in model.columns:
            if column.name in carried and column.name != "_batch_id":
                assert column.classification == carried[column.name], (model.name, column.name)
            assert f"Classification: `{column.classification}`" in column.description


def test_interchange_rates_expose_business_validity_half_open():
    model = next(m for m in silver_generate.build() if m.name == "sl_interchange_rates")
    sql = silver_generate.render_sql(model)
    assert "business_valid_to('valid_to_date')" in sql
    names = [c.name for c in model.columns]
    assert "_business_valid_from_date" in names and "_business_valid_to_date" in names


def test_the_inventory_section_lists_every_generated_model_with_a_consumer():
    text = (ROOT / "docs" / "model_inventory.md").read_text(encoding="utf-8")
    section = text.split(silver_generate.BEGIN, 1)[1].split(silver_generate.END, 1)[0]
    rows = [line for line in section.splitlines() if line.startswith("| `sl_")]
    assert len(rows) == GENERATED_SQL
    assert all(not line.rstrip().endswith("|  |") for line in rows)
