"""Generate the bronze dbt models from the contracts (spec 007 section 4).

The contracts are the one source for what bronze carries: its entities, columns, types, keys
and classifications. Hand-writing fifty models and their properties would be a second copy of
all of it, maintained by nobody, so this writes them:

- `dbt/models/bronze/br_<source>__<entity>.sql`, which is one call to the read macro;
- `dbt/models/bronze/br_<source>__<entity>.yml`, the model's columns, types, descriptions and
  classifications, its grain and its tests;
- `dbt/models/bronze/_sources.yml`, `ops.batch_registry`, the one platform table dbt reads;
- the bronze section of `docs/model_inventory.md`, between its markers.

The files are committed so a reviewer reads what dbt runs, and `--check` regenerates them in
memory and fails on any difference, so a hand edit or a contract changed without regenerating
fails in CI. That is the `schema-check` pattern: one source, one mechanical check.

**Columns across contract versions.** A model carries the union of every version's columns, in
the order they first appear, each typed as in the latest version that carries it. A column one
version retired stays, null for deliveries from the day it was retired; one a version added is
null for deliveries before it. Both are described by delivery date, because a contract is chosen
by the day the sender produced the delivery (ADR 0016): a late file for a settlement date before
a change, sent after it, is in the new layout.

**Identifier columns are typed as tokens.** The contract types an identifier as the cleartext it
describes, `character(12)` for a card reference, and bronze holds a token of the tokeniser's
width in its place, so the model says so rather than repeating a type no value in it has.

**Descriptions.** A `core` or `ref` column takes its description from `docs/data_dictionary.md`,
the one source for what the relational source is. A feed's contract carries no column
descriptions, and adding them would change files whose versions warehouses have recorded, so a
feed column is described from what its contract states: the source it is part of, where in the
delivery it comes from, and its classification. Every description states the classification,
because the published documentation site shows descriptions everywhere.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "airflow" / "plugins"))

from data_contract import (  # noqa: E402
    AUDIT_COLUMNS,
    AUDIT_MEANING,
    PAYLOAD_COLUMN,
    PLATFORM_COLUMN_TYPES,
    RELATIONAL,
    load_history,
    type_family,
)
from schema_contract import read_dictionary  # noqa: E402

CONTRACTS = ROOT / "contracts"
MODELS = ROOT / "dbt" / "models" / "bronze"
INVENTORY = ROOT / "docs" / "model_inventory.md"
DICTIONARY = ROOT / "docs" / "data_dictionary.md"

BEGIN = "<!-- bronze models: generated by scripts/dbt_generate.py, do not edit by hand -->"
END = "<!-- end of generated bronze models -->"
REFERENCE_LISTING = "## Reference tables and the dimensions that consume them"

# The two columns the read macro adds from the object key. Named with the underscore every
# platform column takes, and never a contract column's name.
KEY_BATCH = "_object_batch_id"
KEY_DATE = "_object_ingest_date"

# Most protective first. `_raw_payload` carries every field of the record, so it takes the most
# protective class among the columns it carries; an identifier is a token inside it.
PROTECTION = ("sensitive", "quasi-identifier", "identifier", "pseudonymous_key", "non-personal")

CLASS_NOTE = {
    "identifier": "tokenised at extraction",
    "quasi-identifier": "retained in the clear, generalised before gold",
    "sensitive": "retained at full precision, never exported",
    "pseudonymous_key": "a key to a person-bearing entity, retained unchanged",
    "non-personal": "no restriction",
}

ORIGIN_NOTE = {
    "record": "a field of each record",
    "header": "a field of the delivery's header, carried by every record of it",
    "request": "what was requested, carried by every record of the response",
}


def token_width() -> int:
    from nordbank_ops.tokenise import TOKEN_WIDTH

    return TOKEN_WIDTH


def duckdb_type(declared: str) -> str:
    """The DuckDB type a contract's declared type is cast to in bronze."""
    family = type_family(declared)
    if family.kind == "text":
        return "VARCHAR"
    if family.kind == "integer":
        return {16: "SMALLINT", 32: "INTEGER", 64: "BIGINT"}[family.precision]
    if family.kind == "decimal":
        return f"DECIMAL({family.precision},{family.scale})"
    if family.kind == "timestamptz":
        return "TIMESTAMP WITH TIME ZONE"
    return {"date": "DATE", "boolean": "BOOLEAN", "json": "JSON", "double": "DOUBLE"}[family.kind]


@dataclass
class Column:
    name: str
    data_type: str
    classification: str
    description: str


@dataclass
class Model:
    source_system: str
    entity: str
    kind: str
    contract_path: str
    versions: list = field(default_factory=list)
    columns: list[Column] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"br_{self.source_system}__{self.entity}"

    @property
    def current(self):
        return self.versions[-1]

    @property
    def grain(self) -> list[str]:
        return [*self.current.keys, "_batch_id"]

    @property
    def identifiers(self) -> list[str]:
        return [c.name for c in self.columns if c.classification == "identifier"]


def _dictionary() -> dict[tuple[str, str, str], str]:
    return {(c.schema, c.table, c.name): c.description for c in read_dictionary(DICTIONARY)}


def _sentence(text: str) -> str:
    text = text.strip()
    return text if not text or text.endswith(".") else text + "."


def _span(model: Model, name: str) -> str:
    """When the column is delivered, by contract version and delivery date."""
    carried = [v for v in model.versions if v.column(name) is not None]
    if len(carried) == len(model.versions):
        return ""
    first, last = carried[0], carried[-1]
    after = model.versions.index(last) + 1
    parts = []
    if model.versions.index(first) > 0:
        parts.append(
            f"Added by contract version {first.contract_version}: null for deliveries before "
            f"{first.in_force_from.isoformat()}."
        )
    if after < len(model.versions):
        retiring = model.versions[after]
        parts.append(
            f"Retired by contract version {retiring.contract_version}: null for deliveries from "
            f"{retiring.in_force_from.isoformat()}, which the sender produced without it."
        )
    return " ".join(parts)


def _base_description(model: Model, name: str, dictionary) -> str:
    contract = next(v for v in reversed(model.versions) if v.column(name) is not None)
    if model.kind == RELATIONAL:
        text = dictionary.get((contract.source_schema, model.entity, name), "")
        if not text:
            raise SystemExit(
                f"dbt-generate: {contract.source_schema}.{model.entity}.{name} has no "
                "description in docs/data_dictionary.md"
            )
        return _sentence(text)
    origin = contract.column(name).origin
    document = (contract.source_of_truth or {}).get("document", "the contract's source of truth")
    return f"`{name}`: {ORIGIN_NOTE[origin]}, as {document} defines it."


def _describe(model: Model, name: str, classification: str, dictionary) -> str:
    parts = [_base_description(model, name, dictionary)]
    if classification == "identifier":
        parts.append(
            f"Holds a token, {token_width()} lowercase hexadecimal characters of a keyed hash "
            "of the cleartext, never the cleartext; the token resolves only through the vault."
        )
    parts.append(f"Classification: `{classification}` ({CLASS_NOTE[classification]}).")
    span = _span(model, name)
    if span:
        parts.append(span)
    return " ".join(parts)


def build_models() -> list[Model]:
    dictionary = _dictionary()
    models = []
    for directory in sorted(p for p in CONTRACTS.iterdir() if p.is_dir()):
        for entity, versions in sorted(load_history(directory).items()):
            current = versions[-1]
            model = Model(
                source_system=current.source_system,
                entity=entity,
                kind=current.kind,
                contract_path=f"contracts/{directory.name}/{entity}.yml",
                versions=list(versions),
            )
            order: list[str] = []
            for version in versions:
                for column in version.columns:
                    if column.name not in order:
                        order.append(column.name)
            for name in order:
                if name in (KEY_BATCH, KEY_DATE, "batch_id", "ingest_date"):
                    raise SystemExit(f"dbt-generate: {entity}.{name} collides with a key column")
                latest = next(v for v in reversed(versions) if v.column(name) is not None)
                declared = latest.column(name)
                classification = declared.classification
                data_type = (
                    "VARCHAR" if classification == "identifier" else duckdb_type(declared.data_type)
                )
                model.columns.append(
                    Column(
                        name,
                        data_type,
                        classification,
                        _describe(model, name, classification, dictionary),
                    )
                )
            model.columns.extend(_platform_columns(model))
            models.append(model)
    return models


def _platform_columns(model: Model) -> list[Column]:
    out = []
    if model.current.is_authored:
        carried = {c.classification for c in model.columns}
        strictest = next(c for c in PROTECTION if c in carried)
        out.append(
            Column(
                PAYLOAD_COLUMN,
                duckdb_type(PLATFORM_COLUMN_TYPES[PAYLOAD_COLUMN]),
                strictest,
                "The record as received, structurally faithful, with every identifier field "
                "replaced by its token (ADR 0005). It carries every field of the record, so it "
                f"takes the most protective class among them. Classification: `{strictest}` "
                f"({CLASS_NOTE[strictest]}).",
            )
        )
    for name in AUDIT_COLUMNS:
        meaning = AUDIT_MEANING[name][model.kind]
        out.append(
            Column(
                name,
                duckdb_type(PLATFORM_COLUMN_TYPES[name]),
                "non-personal",
                f"Audit column: {meaning}. Classification: `non-personal` (no restriction).",
            )
        )
    out.append(
        Column(
            KEY_BATCH,
            "VARCHAR",
            "non-personal",
            "The `batch_id` of the object key the row was read from. The registered-batch "
            "filter reads this, never the file's `_batch_id`, and a test asserts the two are "
            "equal. Classification: `non-personal` (no restriction).",
        )
    )
    out.append(
        Column(
            KEY_DATE,
            "DATE",
            "non-personal",
            "The `ingest_date` of the object key the row was read from: the logical date of "
            "the ingestion run, a test asserts it equals the registry's. Classification: "
            "`non-personal` (no restriction).",
        )
    )
    return out


# --- rendering --------------------------------------------------------------------------------


def _quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_sql(model: Model) -> str:
    return (
        f"-- Generated by scripts/dbt_generate.py from {model.contract_path}; do not edit.\n"
        f"{{{{ bronze_read('{model.source_system}', '{model.entity}') }}}}\n"
    )


def render_yml(model: Model) -> str:
    versions = ", ".join(str(v.contract_version) for v in model.versions)
    grain = ", ".join(f"`{c}`" for c in model.grain)
    lines = [
        "# Generated by scripts/dbt_generate.py from the contracts; do not edit.",
        "version: 2",
        "models:",
        f"  - name: {model.name}",
        "    description: "
        + _quote(
            f"Bronze {model.entity} from {model.source_system}: every row of every batch "
            f"registered in ops.batch_registry, read from the lake prefix "
            f"bronze/{model.source_system}/{model.entity}/ and cast to the contract "
            f"({model.contract_path}, version(s) {versions}). Grain: {grain}; the same key "
            "recurs across batches by design."
        ),
        "    config:",
        "      meta:",
        f"        source_system: {model.source_system}",
        f"        entity: {model.entity}",
        f"        ingestion_mode: {model.kind}",
        f"        contract_versions: [{versions}]",
        f"        grain: [{', '.join(model.grain)}]",
        "    data_tests:",
        "      - bronze_unique_key:",
        "          arguments:",
        f"            columns: [{', '.join(model.grain)}]",
        "          config:",
        "            severity: error",
        "      - bronze_not_null:",
        "          name: " + f"{model.name}_grain_not_null",
        "          arguments:",
        f"            columns: [{', '.join(model.grain)}]",
        "          config:",
        "            severity: error",
        "      - bronze_not_null:",
        "          name: " + f"{model.name}_audit_not_null",
        "          arguments:",
        f"            columns: [{', '.join(AUDIT_COLUMNS)}]",
        "          config:",
        "            severity: error",
        "      - bronze_landing_reconciliation:",
        "          arguments:",
        f"            source_system: {model.source_system}",
        f"            entity: {model.entity}",
        "          config:",
        "            severity: error",
        "      - bronze_hive_key:",
        "          config:",
        "            severity: error",
        "    columns:",
    ]
    for column in model.columns:
        lines += [
            f"      - name: {column.name}",
            f"        data_type: {column.data_type}",
            "        description: " + _quote(column.description),
            "        config:",
            "          meta:",
            f"            classification: {column.classification}",
        ]
        # The token test is for the contract's identifier columns. The payload can take the
        # identifier class as the most protective it carries, and holds JSON or a CSV line.
        if column.classification == "identifier" and column.name != PAYLOAD_COLUMN:
            lines += [
                "        data_tests:",
                "          - bronze_token:",
                "              arguments:",
                f"                width: {token_width()}",
                "              config:",
                "                severity: error",
            ]
    return "\n".join(lines) + "\n"


def render_sources() -> str:
    return (
        "# Generated by scripts/dbt_generate.py; do not edit.\n"
        "version: 2\n"
        "sources:\n"
        "  - name: ops\n"
        "    schema: ops\n"
        "    description: "
        + _quote(
            "Pipeline state written by the ingestion DAGs (specification 005). Only the batch "
            "registry is declared: it is the one platform table a bronze model or test reads. "
            "meta.pii_vault is never declared and never read by dbt."
        )
        + "\n"
        "    tables:\n"
        "      - name: batch_registry\n"
        "        description: "
        + _quote(
            "One row per extraction batch. Only a batch in status `registered` is readable "
            "downstream, and every bronze model reads through this filter."
        )
        + "\n"
    )


def render_inventory(models: list[Model], text: str) -> str:
    """The inventory with its bronze section regenerated between the markers."""
    consumers = _consumers(text)
    for model in models:
        if not consumers.get(model.name):
            raise SystemExit(
                f"dbt-generate: {model.name} has no consumer in docs/model_inventory.md or "
                "docs/data_dictionary.md; the coverage rule in business_questions.md needs one"
            )
    rows = [
        "| Object | Grain | Lake prefix | Contract versions | Consumed by |",
        "|---|---|---|---|---|",
    ]
    for model in models:
        grain = ", ".join(f"`{c}`" for c in model.grain)
        versions = ", ".join(str(v.contract_version) for v in model.versions)
        rows.append(
            f"| `{model.name}` | {grain} | `bronze/{model.source_system}/{model.entity}/` | "
            f"{versions} | {'; '.join(sorted(consumers[model.name]))} |"
        )
    block = "\n".join(
        [
            BEGIN,
            "",
            f"{len(models)} models, one per contract entity, generated from `contracts/`. Each is "
            "a view over its lake prefix that keeps only registered batches (ADR 0018).",
            "",
            *rows,
            "",
            END,
        ]
    )
    if BEGIN not in text or END not in text:
        raise SystemExit("dbt-generate: docs/model_inventory.md has no bronze markers")
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


def _consumers(text: str) -> dict[str, set[str]]:
    """Who reads each bronze model: the planned models whose upstream names it, from the
    hand-written sections of the inventory, and for a relational entity the consumers the
    data dictionary names for its columns."""
    head = text.split(BEGIN, 1)[0] + text.split(END, 1)[-1]
    out: dict[str, set[str]] = defaultdict(set)
    for line in head.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or not cells[0].startswith("`"):
            continue
        for name in re.findall(r"`(br_[a-z_]+__[a-z_]+)`", " | ".join(cells[1:])):
            out[name].add(cells[0])
    for column in read_dictionary(DICTIONARY):
        if column.consumed_by and column.consumed_by != "-":
            out[f"br_corebank__{column.table}"].update(
                part.strip() for part in column.consumed_by.split(";") if part.strip()
            )
    # The dictionary's list of reference tables names the dimension or fact each one feeds.
    listing = DICTIONARY.read_text(encoding="utf-8").split(REFERENCE_LISTING, 1)[-1]
    for line in listing.split("\n## ", 1)[0].splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].startswith("`") and cells[2] != "Consumed by":
            out[f"br_corebank__{cells[0].strip('`')}"].add(cells[2])
    return out


def outputs() -> dict[Path, str]:
    models = build_models()
    files = {MODELS / "_sources.yml": render_sources()}
    for model in models:
        files[MODELS / f"{model.name}.sql"] = render_sql(model)
        files[MODELS / f"{model.name}.yml"] = render_yml(model)
    files[INVENTORY] = render_inventory(models, INVENTORY.read_text(encoding="utf-8"))
    return files


def _shown(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)

    wanted = outputs()
    generated = {p for p in MODELS.glob("br_*")} | {MODELS / "_sources.yml"}
    stale = sorted(generated - set(wanted))
    if arguments.check:
        differing = [
            path
            for path, text in wanted.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        for path in differing + stale:
            print(f"dbt-generate: {_shown(path)} differs from the contracts")
        if differing or stale:
            print("dbt-generate: run `make dbt-generate` and commit the result")
            return 1
        models = sum(1 for p in wanted if p.suffix == ".sql")
        print(f"dbt-generate: {models} bronze models and the inventory agree with the contracts")
        return 0

    MODELS.mkdir(parents=True, exist_ok=True)
    for path in stale:
        path.unlink()
    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8", newline="\n")
    print(f"dbt-generate: wrote {len(wanted)} file(s), removed {len(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
