"""Generate the silver models that mirror a contract entity (specification 008 sections 2 and 5).

The contracts are the one source for what an entity carries, and `scripts/dbt_generate.py`
already reads them into the bronze models' columns, types, descriptions and classifications.
This builds on its `build_models()` and writes, for every silver model that mirrors one
relational entity:

- the model's properties, `dbt/models/silver/sl_<entity>.yml`: every column silver carries, with
  the bronze column's type, description and classification, the columns silver adds, its grain,
  its tests and its minimum cardinality; every silver model's contract is enforced
  (`dbt_project.yml`), so a model whose SQL returns anything else fails to build;
- for every `ref` table and for `agent_locations`, the model itself, `sl_<entity>.sql`, which is
  one call to the historisation macro: their silver is the contract's columns historised and
  nothing more, so writing them by hand would be thirty copies of one line;
- the generated section of the inventory's silver listing, between its markers.

A model with logic of its own, such as `sl_transactions`, which converts its amount, is written
by hand: this generates its properties and leaves its SQL alone, and the enforced contract holds
the two together.

`--check` regenerates everything in memory and fails on any difference, so a hand edit to a
generated file, or a contract changed without regenerating, fails in CI: the `dbt-generate`
pattern. Run it before `make dbt-generate`, whose bronze consumer lists read this section.

**What a mirroring model carries.** Its key, every contract column of its projection, the
version's `created_at` and `updated_at`, the `_batch_id` that read it, and for SCD2 the validity
columns. It does not carry `is_deleted`, which is false on every row silver keeps, the excluded
measures, which open no version and are wrong on every row but the one that opened it, or the
other audit columns, which describe a read rather than the entity.

**The external feeds** (specification 009) are not entities with versions: a clearing file's
records, a list snapshot's entities and a series' observations. Their silver is written by hand,
and `FEEDS` states, for each, the bronze columns it carries, under the same or a new name and
type, the columns it adds, its grain and its floor; their properties are generated from that and
the feed contracts the same way, so a column's type, description and classification still have
one source.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "airflow" / "plugins"))

import dbt_generate  # noqa: E402
import yaml  # noqa: E402
from data_contract import RELATIONAL  # noqa: E402

MODELS = ROOT / "dbt" / "models" / "silver"
INVENTORY = ROOT / "docs" / "model_inventory.md"
# The quasi-identifier columns permitted in gold and their generalisations (review of 008).
GOLD_PERMITTED = ROOT / "dbt" / "quasi_identifiers_in_gold.yml"
DICTIONARY = ROOT / "docs" / "data_dictionary.md"

BEGIN = "<!-- silver models: generated by scripts/silver_generate.py, do not edit by hand -->"
END = "<!-- end of generated silver models -->"

SCD2 = "scd2"
LATEST = "latest_state"

# The columns bronze carries for the platform, which silver does not mirror. `_batch_id` is
# carried, with its own meaning, and so are the two audit stamps.
NOT_MIRRORED = (
    "is_deleted",
    "_ingested_at",
    "_source_file",
    "_source_system",
    "_object_batch_id",
    "_object_ingest_date",
    "_raw_payload",
)
STAMPS = ("created_at", "updated_at", "_batch_id")

NON_PERSONAL = "non-personal"


@dataclass(frozen=True)
class Added:
    """A column silver adds to the entity's own."""

    name: str
    data_type: str
    description: str
    classification: str = NON_PERSONAL


@dataclass(frozen=True)
class Spec:
    """How one entity's silver model is built.

    `floor` is the model's minimum cardinality, a number stated here and never read from the
    data: for a `ref` table its seeded row count, for the rest a floor the `ci` book clears on its
    first day. `generated` models are one macro call; the rest are written by hand.
    """

    entity: str
    history: str
    floor: int
    excluded: tuple[str, ...] = ()
    added: tuple[Added, ...] = ()
    generated: bool = False
    deleted: str = "is_deleted"
    # A fact's business instant, the dimension versions it must resolve to at that instant
    # (column, silver model, that model's column), and the amount it converts to EUR with its
    # currency column.
    instant: str = ""
    resolves: tuple[tuple[str, str, str], ...] = ()
    converts: tuple[str, str] | None = None
    # A derived boolean and the floors each side must clear: (column, minimum true, minimum false).
    splits: tuple[tuple[str, int, int], ...] = ()


SCD2_COLUMNS = (
    Added(
        "_valid_from",
        "TIMESTAMP WITH TIME ZONE",
        "When this version opens: the `updated_at` of the observation that opened it, except the "
        "key's first version, which opens at the epoch, 1900-01-01T00:00:00Z, because the first "
        "observed state is backdated as the earliest known state, not the true state.",
    ),
    Added(
        "_valid_to",
        "TIMESTAMP WITH TIME ZONE",
        "When this version closes, exclusive: the next version's opening, the instant a soft "
        "delete was recorded, or 9999-12-31T00:00:00Z while current. Never null.",
    ),
    Added(
        "_is_current",
        "BOOLEAN",
        "Whether this is the key's current version. A soft-deleted key has none.",
    ),
)

# The `ref` tables' seeded row counts at this commit, each a version at the epoch. A `ref` table
# with no floor here fails generation rather than going untested.
REFERENCE_FLOORS = {
    "account_statuses": 5,
    "account_types": 8,
    "card_product_classes": 5,
    "card_products": 7,
    "channels": 7,
    "countries": 30,
    "currencies": 9,
    "decision_reasons": 9,
    "entry_sides": 2,
    "fraud_dispositions": 5,
    "fraud_rules": 7,
    "gl_account_types": 5,
    "gl_accounts": 17,
    "gl_source_entities": 2,
    "holder_roles": 3,
    "interchange_rates": 210,
    "loan_application_statuses": 7,
    "loan_products": 6,
    "loan_statuses": 6,
    "login_outcomes": 5,
    "mcc_bands": 7,
    "mcc_codes": 22,
    "payment_schemes": 5,
    "payment_statuses": 7,
    "payment_types": 10,
    "regions": 6,
    "risk_bands": 5,
    "transaction_statuses": 6,
    "transaction_types": 18,
}


def business_validity(classification: str) -> tuple[Added, ...]:
    """The half-open business validity a source with an inclusive last day is exposed as
    (specification 008 section 3), classified as the dates it is derived from."""
    return (
        Added(
            "_business_valid_from_date",
            "DATE",
            "First day the row applies in business time: `valid_from_date`.",
            classification,
        ),
        Added(
            "_business_valid_to_date",
            "DATE",
            "The day after the last day the row applies in business time, exclusive: "
            "`valid_to_date` plus one day, or 9999-12-31 while open. The source's last day is "
            "inclusive; silver exposes it half-open so a fact joins with `>=` and `<`, on the "
            "current system-time version.",
            classification,
        ),
    )


REFERENCE_ADDED = {"interchange_rates": business_validity(NON_PERSONAL)}

# Core banking entities whose silver is historisation alone, generated like the `ref` tables.
GENERATED_CORE = {"agent_locations": 3}


def fx_columns(prefix: str) -> tuple[Added, ...]:
    """The converted amount and its provenance (specification 008 section 6)."""
    return (
        Added(
            f"{prefix}_amount_eur",
            "DECIMAL(18,4)",
            f"`{prefix}_amount` in EUR: divided by the latest rate published at or before the "
            "business instant, in exact integer arithmetic, rounded half away from zero to four "
            "places. The amount itself for EUR; null when no rate was published before the "
            "instant, never zero and never the original amount.",
        ),
        Added(
            "fx_rate",
            "DECIMAL(18,8)",
            "The rate converted at, in currency per euro; 1 for EUR; null when missing.",
        ),
        Added(
            "fx_rate_date",
            "DATE",
            "The date of the rate converted at. Null for EUR and when missing.",
        ),
        Added(
            "fx_is_carried",
            "BOOLEAN",
            "The rate's date is not the business instant's UTC date: carried across a weekend "
            "or a holiday, or from the day before when the fact precedes the day's publication.",
        ),
        Added(
            "fx_is_missing",
            "BOOLEAN",
            "No rate for the currency was published at or before the business instant.",
        ),
        Added(
            "fx_is_provisional",
            "BOOLEAN",
            "The rate's date is the feed's latest publication date, across every currency, and "
            "the business instant is after the publication instant of the next weekday after it: "
            "the next publication has not landed, and a rebuild may restate this row. Once a later "
            "publication has landed the conversion is final, whether or not it carries the "
            "currency. Never true for EUR or a missing rate.",
        ),
    )


def customer_initiated(types: str, instant: str) -> Added:
    """The type's customer-initiated flag, read as of the fact (traceability gap 1)."""
    return Added(
        "is_customer_initiated",
        "BOOLEAN",
        f"Whether the customer, rather than the bank, initiated it: the flag of the version of "
        f"`{types}` in force at `{instant}`, the one source of the flag.",
    )


# A ledger row's instant: the start of its posting date, in UTC.
POSTING_INSTANT = "timezone('UTC', cast(posting_date as timestamp))"

# Entities whose silver is written by hand; the properties are still generated from here. The
# floors sit below what the `ci` book lands on its first day (customers 500, addresses 590,
# accounts 566, holders 637, cards 341, merchants 120, loans 11, installments 528), so the stack
# job's week clears them and an empty or truncated build does not.
HAND_WRITTEN: tuple[Spec, ...] = (
    Spec("customers", SCD2, 400),
    Spec(
        "customer_addresses",
        SCD2,
        450,
        added=business_validity("quasi-identifier")
        + (
            Added(
                "postal_district",
                "VARCHAR",
                "The postal code generalised to its first two characters, `left(postal_code, 2)`: "
                "the district reporting uses in place of the full code, which is a "
                "quasi-identifier and never leaves silver. A deliberate simplification, since EU "
                "postcode formats differ.",
            ),
        ),
    ),
    Spec("accounts", SCD2, 450, excluded=("current_balance_amount",)),
    Spec("account_holders", SCD2, 500),
    Spec("cards", SCD2, 250),
    Spec(
        "merchants",
        SCD2,
        100,
        added=(
            Added(
                "merchant_name_normalised",
                "VARCHAR",
                "`merchant_name` in one representation: upper case, accents removed, surrounding "
                "whitespace trimmed and runs of whitespace collapsed to one space. The raw name "
                "stays beside it. Representation only: the store numbers, locations and legal "
                "forms an acquirer appends are kept, because deciding that two descriptors name "
                "one merchant is entity resolution, specification 010.",
            ),
        ),
    ),
    Spec("loans", SCD2, 5),
    Spec("loan_installments", SCD2, 400),
    # Latest state. Floors below the `ci` book's first day: transactions 31,473, payments 6,062,
    # applications 21, alerts 21, sessions 20,139, posting batches 34,287, ledger lines 68,600.
    Spec(
        "transactions",
        LATEST,
        25000,
        added=(customer_initiated("sl_transaction_types", "booked_at"),)
        + fx_columns("transaction"),
        instant="booked_at",
        resolves=(
            ("account_id", "sl_accounts", "account_id"),
            ("card_id", "sl_cards", "card_id"),
            ("merchant_id", "sl_merchants", "merchant_id"),
            ("agent_location_id", "sl_agent_locations", "agent_location_id"),
            ("transaction_type_code", "sl_transaction_types", "code"),
            ("channel_code", "sl_channels", "code"),
            ("transaction_status_code", "sl_transaction_statuses", "code"),
            ("transaction_currency_code", "sl_currencies", "code"),
        ),
        converts=("transaction_amount", "transaction_currency_code"),
        # The `ci` book's first day: 28,012 customer-initiated transactions and 3,408 not.
        splits=(("is_customer_initiated", 22000, 2500),),
    ),
    Spec(
        "payments",
        LATEST,
        5000,
        added=(customer_initiated("sl_payment_types", "initiated_at"),) + fx_columns("payment"),
        instant="initiated_at",
        resolves=(
            ("account_id", "sl_accounts", "account_id"),
            ("payment_type_code", "sl_payment_types", "code"),
            ("payment_scheme_code", "sl_payment_schemes", "code"),
            ("payment_status_code", "sl_payment_statuses", "code"),
            ("payment_currency_code", "sl_currencies", "code"),
        ),
        converts=("payment_amount", "payment_currency_code"),
        # The `ci` book's first day: 5,720 customer-initiated payments and 61 not.
        splits=(("is_customer_initiated", 4500, 40),),
    ),
    Spec(
        "loan_applications",
        LATEST,
        10,
        instant="applied_at",
        resolves=(
            ("customer_id", "sl_customers", "customer_id"),
            ("loan_product_code", "sl_loan_products", "code"),
            ("loan_application_status_code", "sl_loan_application_statuses", "code"),
            ("risk_band_code", "sl_risk_bands", "code"),
            ("decision_reason_code", "sl_decision_reasons", "code"),
            ("application_currency_code", "sl_currencies", "code"),
        ),
    ),
    Spec(
        "fraud_alerts",
        LATEST,
        10,
        instant="alerted_at",
        resolves=(
            ("customer_id", "sl_customers", "customer_id"),
            ("fraud_rule_code", "sl_fraud_rules", "code"),
            ("fraud_disposition_code", "sl_fraud_dispositions", "code"),
        ),
    ),
    Spec(
        "login_sessions",
        LATEST,
        15000,
        instant="started_at",
        resolves=(
            ("customer_id", "sl_customers", "customer_id"),
            ("channel_code", "sl_channels", "code"),
            ("login_outcome_code", "sl_login_outcomes", "code"),
        ),
    ),
    Spec(
        "gl_transactions",
        LATEST,
        30000,
        instant=POSTING_INSTANT,
        resolves=(("source_entity_code", "sl_gl_source_entities", "code"),),
    ),
    Spec(
        "gl_entries",
        LATEST,
        60000,
        instant=POSTING_INSTANT,
        resolves=(
            ("account_id", "sl_accounts", "account_id"),
            ("gl_account_code", "sl_gl_accounts", "code"),
            ("entry_side_code", "sl_entry_sides", "code"),
            ("entry_currency_code", "sl_currencies", "code"),
        ),
    ),
)


# --- the external feeds (specification 009) ---------------------------------------------------


@dataclass(frozen=True)
class Carried:
    """A bronze column a feed model carries: under its own name or `name`, in the bronze type or
    `data_type`, with `note` appended to the bronze description where silver changes it."""

    source: str
    name: str = ""
    data_type: str = ""
    note: str = ""

    @property
    def silver_name(self) -> str:
        return self.name or self.source


@dataclass(frozen=True)
class Feed:
    """A silver model over a feed's bronze entity, written by hand.

    `floor` is a number stated here, below what the stack job's week lands. A feed that may never
    land, FRED without a key, states `floor_once_registered` instead: the floor applies only
    once a batch of the entity is registered, and the test says so.
    """

    name: str
    upstream: str
    grain: tuple[str, ...]
    floor: int
    description: str
    columns: tuple[Carried | Added, ...]
    floor_once_registered: tuple[str, str] | None = None


def _batch(meaning: str) -> Carried:
    return Carried("_batch_id", note=f"In silver, {meaning}")


# The batch arithmetic and resolution are the settlement macros' (dbt/macros/settlement.sql). The
# floors sit below the stack job's week, 2026-07-20 to 2026-07-26: 926 winning lines and 60
# trailers.
SETTLEMENT_HEADER = ("settlement_date", "file_sequence", "processor_id", "revision",
                     "file_created_at")  # fmt: skip
FEEDS: tuple[Feed, ...] = (
    Feed(
        "sl_card_settlements",
        "br_cardnet__settlements",
        ("settlement_date", "file_sequence", "transaction_reference"),
        700,
        "Silver card settlement lines, from `br_cardnet__settlements` "
        "(contracts/cardnet/settlements.yml). Every detail line of each settlement date and "
        "sender sequence's winning revision: the highest revision declared in bronze, across "
        "lines and trailers together, whatever order the files arrived in; lines of different "
        "sequences add. Each line is resolved to its card, transaction and merchant without "
        "correction, and a line that resolves to nothing is kept with nulls. Amounts stay in the "
        "settlement currency at source precision: detection never converts.",
        (
            *(
                Carried(c)
                for c in (
                    "record_type",
                    "transaction_reference",
                    "transaction_date",
                    "clearing_date",
                    "network",
                    "card_reference",
                    "masked_pan",
                    "merchant_category_code",
                )
            ),
            Carried(
                "merchant_name",
                note="In silver, as landed: null on every line of a file sent after the "
                "processor retired the field on 2026-09-03 at the acceptance anchor, and never "
                "back-filled. The merchant is `merchant_id`.",
            ),
            *(Carried(c) for c in ("presentment", "settlement_currency", "settlement_amount")),
            *(Carried(c) for c in SETTLEMENT_HEADER),
            _batch("the batch the line landed in, of its winning revision."),
            Added(
                "card_id",
                "BIGINT",
                "The card the line's `card_reference` token names, from the distinct pairs of "
                "token and card in `sl_cards`, never a join to its versions. Null when the bank "
                "holds no card under the token.",
                "pseudonymous_key",
            ),
            Added(
                "transaction_id",
                "BIGINT",
                "The transaction whose `transaction_reference` the line carries, from "
                "`sl_transactions`. Null when the bank holds no such transaction.",
            ),
            Added(
                "merchant_id",
                "BIGINT",
                "The merchant of the line's transaction, from `sl_transactions`. Null for a "
                "cash withdrawal, or when the transaction did not resolve.",
            ),
        ),
    ),
    Feed(
        "sl_card_settlement_totals",
        "br_cardnet__settlement_totals",
        ("settlement_date", "file_sequence", "network", "settlement_currency"),
        45,
        "Silver card settlement totals, from `br_cardnet__settlement_totals` "
        "(contracts/cardnet/settlement_totals.yml). One row per trailer of each settlement date "
        "and sender sequence's winning revision, chosen by the same macro as the lines: the "
        "processor's own count and total per network and settlement currency, over every detail "
        "record it wrote, quarantined ones included. Silver compares nothing: lines against "
        "trailers and trailers against the ledger are the reconciliation mart's (Q15).",
        (
            Carried("record_type"),
            Carried("network"),
            Carried("settlement_currency"),
            Carried("record_count"),
            Carried(
                "amount_total",
                name="file_total_amount",
                note="In silver, `file_total_amount`: the file side of the settlement "
                "reconciliation, signed, negative where refunds outweigh purchases.",
            ),
            *(Carried(c) for c in SETTLEMENT_HEADER),
            _batch("the batch the trailer landed in, of its winning revision."),
        ),
    ),
    # One batch is one whole list version (ADR 0015), so silver keeps every landed version, each
    # entity once in it. Floors below the stack job's week, the 2026-07-20 version alone: 315
    # entities and 431 names.
    Feed(
        "sl_sanctions_entities",
        "br_opensanctions__entities",
        ("entity_id", "publisher_version"),
        300,
        "Silver sanctions list entities, from `br_opensanctions__entities` "
        "(contracts/opensanctions/entities.yml). One row per entity per landed list version, "
        "keyed by the publisher's entity id and version string. The list is synthetic, in the "
        "real feed's shape (ADR 0015). Multi-valued properties stay lists. The entity's names "
        "and aliases are `sl_sanctions_names`; matching them is specification 010's governance "
        "job (ADR 0010).",
        (
            Carried("entity_id"),
            Carried("publisher_version"),
            Carried("published_at"),
            Carried("entity_schema"),
            Carried(
                "caption",
                note="The publisher's display label: the entity's first name, and not a name of "
                "its own in `sl_sanctions_names`.",
            ),
            *(
                Carried(c, data_type="VARCHAR[]", note=note)
                for c, note in (
                    ("datasets", "In silver, a list of text."),
                    ("referents", "In silver, a list of text."),
                    (
                        "topics",
                        "In silver, a list of text: why the entity is listed, such as "
                        "`sanction` or `role.pep`.",
                    ),
                    (
                        "countries",
                        "In silver, a list of text, null where the entity states none: an "
                        "organisation's countries. A person states nationalities instead.",
                    ),
                    (
                        "nationalities",
                        "In silver, a list of text, null where the entity states none: a "
                        "person's nationalities.",
                    ),
                    (
                        "birth_dates",
                        "In silver, a list of text, never dates: FollowTheMoney dates are "
                        "partial, a year or a year and month as often as a day.",
                    ),
                )
            ),
            Carried("first_seen"),
            Carried("last_change"),
            _batch("the batch the list version landed as."),
        ),
    ),
    Feed(
        "sl_sanctions_names",
        "br_opensanctions__entities",
        ("entity_id", "publisher_version", "name"),
        400,
        "Silver sanctions list names, from `br_opensanctions__entities` "
        "(contracts/opensanctions/entities.yml). One row per entity, landed list version and "
        "name: every value of the entity's `names` and `aliases`, with `name_type` saying which, "
        "and the name in the one representation `normalise_name` gives every silver name beside "
        "the raw one. A value stated twice, or as both a name and an alias, is one row, typed "
        "`name`. The caption is not added: it equals the first name.",
        (
            Carried("entity_id"),
            Carried("publisher_version"),
            Added(
                "name_type",
                "VARCHAR",
                "Which of the entity's properties the name was stated in: `name` or `alias`.",
            ),
            Carried(
                "names",
                name="name",
                data_type="VARCHAR",
                note="In silver, one value of the entity's `names` or `aliases` per row, as the "
                "publisher stated it.",
            ),
            Added(
                "name_normalised",
                "VARCHAR",
                "`name` in one representation, by `normalise_name`, the macro merchants use: upper "
                "case, accents removed, whitespace collapsed and trimmed. Representation only; "
                "matching is specification 010's.",
                "sensitive",
            ),
            _batch("the batch the list version landed as."),
        ),
    ),
)


def _added_column(column: Added) -> dbt_generate.Column:
    return dbt_generate.Column(
        column.name,
        column.data_type,
        column.classification,
        f"{column.description} Classification: `{column.classification}` "
        f"({dbt_generate.CLASS_NOTE[column.classification]}).",
    )


@dataclass
class FeedModel:
    feed: Feed
    columns: list[dbt_generate.Column] = field(default_factory=list)


def build_feeds() -> list[FeedModel]:
    bronze = {m.name: m for m in dbt_generate.build_models()}
    out = []
    for feed in FEEDS:
        if feed.upstream not in bronze:
            raise SystemExit(f"silver-generate: {feed.name} reads {feed.upstream}, not a model")
        by_name = {c.name: c for c in bronze[feed.upstream].columns}
        model = FeedModel(feed)
        for column in feed.columns:
            if isinstance(column, Added):
                model.columns.append(_added_column(column))
                continue
            if column.source not in by_name:
                raise SystemExit(
                    f"silver-generate: {feed.name} carries {column.source}, which "
                    f"{feed.upstream} does not have"
                )
            source = by_name[column.source]
            description = source.description
            if column.note:
                description = f"{description} {column.note}"
            model.columns.append(
                dbt_generate.Column(
                    column.silver_name,
                    column.data_type or source.data_type,
                    source.classification,
                    description,
                )
            )
        names = [c.name for c in model.columns]
        if len(names) != len(set(names)) or not set(feed.grain) <= set(names):
            raise SystemExit(f"silver-generate: {feed.name} repeats a column or misses its grain")
        out.append(model)
    return out


def render_feed_yml(model: FeedModel) -> str:
    feed = model.feed
    grain = ", ".join(feed.grain)
    description = f"{feed.description} Grain: " + ", ".join(f"`{c}`" for c in feed.grain) + "."
    lines = [
        "# Generated by scripts/silver_generate.py from the contracts; do not edit.",
        "version: 2",
        "models:",
        f"  - name: {feed.name}",
        "    description: " + _quote(description),
        "    config:",
        "      meta:",
        f"        upstream: {feed.upstream}",
        f"        grain: [{grain}]",
        "        generated_sql: false",
        "    data_tests:",
        "      - silver_unique_key:",
        "          arguments:",
        f"            columns: [{grain}]",
        "          config:",
        "            severity: error",
        "      - silver_not_null:",
        "          arguments:",
        f"            columns: [{grain}]",
        "          config:",
        "            severity: error",
    ]
    if feed.floor_once_registered:
        source_system, entity = feed.floor_once_registered
        lines += [
            "      - silver_min_rows_once_registered:",
            "          arguments:",
            f"            minimum: {feed.floor}",
            "            registry: source('ops', 'batch_registry')",
            f"            source_system: {source_system}",
            f"            entity: {entity}",
        ]
    else:
        lines += [
            "      - silver_min_rows:",
            "          arguments:",
            f"            minimum: {feed.floor}",
        ]
    lines += [
        "          config:",
        "            severity: error",
        "    columns:",
    ]
    for column in model.columns:
        lines += [
            f"      - name: {column.name}",
            f"        data_type: {column.data_type}",
            "        description: " + _quote(column.description),
            "        config:",
            "          meta:",
            f"            classification: {column.classification}",
        ]
    return "\n".join(lines) + "\n"


def specs() -> list[Spec]:
    """Every silver model that mirrors a relational entity, in name order."""
    out = list(HAND_WRITTEN)
    for model in dbt_generate.build_models():
        if model.kind != RELATIONAL:
            continue
        schema = model.current.source_schema
        if schema == "ref":
            if model.entity not in REFERENCE_FLOORS:
                raise SystemExit(f"silver-generate: ref.{model.entity} has no floor")
            out.append(
                Spec(
                    model.entity,
                    SCD2,
                    REFERENCE_FLOORS[model.entity],
                    added=REFERENCE_ADDED.get(model.entity, ()),
                    generated=True,
                    deleted="false",
                )
            )
        elif model.entity in GENERATED_CORE:
            out.append(Spec(model.entity, SCD2, GENERATED_CORE[model.entity], generated=True))
    return sorted(out, key=lambda s: s.entity)


@dataclass
class Silver:
    spec: Spec
    bronze: dbt_generate.Model
    columns: list[dbt_generate.Column] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"sl_{self.spec.entity}"

    @property
    def key(self) -> list[str]:
        return list(self.bronze.current.keys)

    @property
    def grain(self) -> list[str]:
        return self.key + (["_valid_from"] if self.spec.history == SCD2 else [])


def _bronze_by_entity() -> dict[str, dbt_generate.Model]:
    return {m.entity: m for m in dbt_generate.build_models() if m.source_system == "corebank"}


def _stamp(name: str, history: str, bronze: dbt_generate.Column) -> dbt_generate.Column:
    if name == "_batch_id":
        opened = "opened this version" if history == SCD2 else "is the entity's latest"
        return dbt_generate.Column(
            name,
            bronze.data_type,
            NON_PERSONAL,
            f"The earliest batch that read the observation which {opened}: re-reads of one "
            "version collapse to it. Classification: `non-personal` (no restriction).",
        )
    whose = "the observation that opened this version"
    if history != SCD2:
        whose = "the latest observation"
    return dbt_generate.Column(
        name,
        bronze.data_type,
        bronze.classification,
        f"{bronze.description} In silver, the value of {whose}.",
    )


def gold_permitted() -> dict[tuple[str, str], str]:
    """(silver model, column) -> its generalisation, from the declaration file."""
    document = yaml.safe_load(GOLD_PERMITTED.read_text(encoding="utf-8")) or {}
    out = {}
    for entry in document.get("permitted") or []:
        key = (entry["model"], entry["column"])
        if key in out or not str(entry.get("generalisation") or "").strip():
            raise SystemExit(f"silver-generate: {GOLD_PERMITTED.name}: {key} is repeated or "
                             "names no generalisation")  # fmt: skip
        out[key] = str(entry["generalisation"]).strip()
    return out


def build() -> list[Silver]:
    bronze = _bronze_by_entity()
    out = []
    for spec in specs():
        source = bronze[spec.entity]
        silver = Silver(spec, source)
        by_name = {c.name: c for c in source.columns}
        for name in spec.excluded:
            if name not in by_name:
                raise SystemExit(f"silver-generate: {spec.entity}.{name} is not a contract column")
        skipped = set(NOT_MIRRORED) | set(STAMPS) | set(spec.excluded)
        ordered = silver.key + [c.name for c in source.columns if c.name not in silver.key]
        for name in ordered:
            if name in skipped:
                continue
            silver.columns.append(by_name[name])
        for name in STAMPS:
            silver.columns.append(_stamp(name, spec.history, by_name[name]))
        added = (SCD2_COLUMNS if spec.history == SCD2 else ()) + spec.added
        for column in added:
            silver.columns.append(
                dbt_generate.Column(
                    column.name,
                    column.data_type,
                    column.classification,
                    f"{column.description} Classification: `{column.classification}` "
                    f"({dbt_generate.CLASS_NOTE[column.classification]}).",
                )
            )
        names = [c.name for c in silver.columns]
        if len(names) != len(set(names)):
            raise SystemExit(f"silver-generate: {silver.name} declares a column twice")
        out.append(silver)
    permitted = gold_permitted()
    classes = {(m.name, c.name): c.classification for m in out for c in m.columns}
    for key in permitted:
        if key not in classes:
            raise SystemExit(
                f"silver-generate: {GOLD_PERMITTED.name} permits {key[0]}.{key[1]}, which is not a "
                "column of a silver model this generates"
            )
        if classes[key] != "quasi-identifier":
            raise SystemExit(
                f"silver-generate: {GOLD_PERMITTED.name} permits {key[0]}.{key[1]}, classified "
                f"{classes[key]}: only a quasi-identifier needs a declared generalisation"
            )
    return out


# --- rendering --------------------------------------------------------------------------------

_quote = dbt_generate._quote


def render_sql(silver: Silver) -> str:
    spec = silver.spec
    key = ", ".join(f"'{k}'" for k in silver.key)
    call = f"{spec.history}(ref('{silver.bronze.name}'), [{key}]"
    if spec.excluded:
        call += ", excluded=[" + ", ".join(f"'{e}'" for e in spec.excluded) + "]"
    if spec.deleted != "is_deleted":
        call += f", deleted='{spec.deleted}'"
    call += ")"
    header = (
        f"-- Generated by scripts/silver_generate.py from {silver.bronze.contract_path}; "
        "do not edit.\n"
    )
    if not any(a.name == "_business_valid_from_date" for a in spec.added):
        return header + f"{{{{ {call} }}}}\n"
    return (
        header
        + "select\n"
        + "    *,\n"
        + "    valid_from_date as _business_valid_from_date,\n"
        + "    {{ business_valid_to('valid_to_date') }} as _business_valid_to_date\n"
        + f"from (\n    {{{{ {call} }}}}\n)\n"
    )


def _describe_model(silver: Silver) -> str:
    spec = silver.spec
    grain = ", ".join(f"`{c}`" for c in silver.grain)
    if spec.history == SCD2:
        kind = (
            "One row per version (SCD2): a version opens when a projection column changes, or "
            "when no contract column changed at all"
        )
        if spec.excluded:
            kind += "; a change confined to " + ", ".join(f"`{e}`" for e in spec.excluded)
            kind += " opens none, and it is not carried"
        kind += "."
    else:
        kind = "One row per entity, its latest observation; a soft-deleted entity is absent."
    if spec.deleted == "false":
        deleted = " An inactive row is retained as a version, current with `is_active` false."
    elif spec.history == SCD2:
        deleted = " A soft delete closes the final version and leaves no current one."
    else:
        deleted = ""
    return (
        f"Silver {spec.entity}, from `{silver.bronze.name}` ({silver.bronze.contract_path}). "
        f"{kind}{deleted} Re-reads of one version collapse to the earliest batch. "
        f"Grain: {grain}."
    )


def render_yml(silver: Silver) -> str:
    spec = silver.spec
    grain = ", ".join(silver.grain)
    key = ", ".join(silver.key)
    lines = [
        "# Generated by scripts/silver_generate.py from the contracts; do not edit.",
        "version: 2",
        "models:",
        f"  - name: {silver.name}",
        "    description: " + _quote(_describe_model(silver)),
        "    config:",
        "      meta:",
        f"        entity: {spec.entity}",
        f"        history: {spec.history}",
        f"        upstream: {silver.bronze.name}",
        f"        grain: [{grain}]",
        f"        excluded: [{', '.join(spec.excluded)}]",
        f"        generated_sql: {'true' if spec.generated else 'false'}",
        "    data_tests:",
        "      - silver_unique_key:",
        "          arguments:",
        f"            columns: [{grain}]",
        "          config:",
        "            severity: error",
        "      - silver_not_null:",
        "          arguments:",
        f"            columns: [{grain}]",
        "          config:",
        "            severity: error",
        "      - silver_min_rows:",
        "          arguments:",
        f"            minimum: {spec.floor}",
        "          config:",
        "            severity: error",
        "      - silver_rereads_agree:",
        "          arguments:",
        f"            upstream: ref('{silver.bronze.name}')",
        f"            key: [{key}]",
        "          config:",
        "            severity: error",
    ]
    if spec.history == SCD2:
        lines += [
            "      - silver_scd2_intervals:",
            "          arguments:",
            f"            key: [{key}]",
            f"            upstream: ref('{silver.bronze.name}')",
        ]
        if spec.deleted != "is_deleted":
            lines.append(f'            deleted: "{spec.deleted}"')
        lines += [
            "          config:",
            "            severity: error",
        ]
    # With no excluded measure every observation that is not a soft delete opens a version, the
    # merchants case included; with one, a singular test checks the rule against bronze.
    if spec.history == SCD2 and not spec.excluded:
        lines += [
            "      - silver_observations_versioned:",
            "          arguments:",
            f"            upstream: ref('{silver.bronze.name}')",
            f"            key: [{key}]",
        ]
        if spec.deleted != "is_deleted":
            lines.append(f'            deleted: "{spec.deleted}"')
        lines += [
            "          config:",
            "            severity: error",
        ]
    if spec.converts:
        amount, currency = spec.converts
        lines += [
            "      - silver_fx_provenance:",
            "          arguments:",
            f"            key: {silver.key[0]}",
            f"            amount: {amount}",
            f"            currency: {currency}",
            "          config:",
            "            severity: error",
        ]
    lines.append("    columns:")
    resolves = {column: (to, to_column) for column, to, to_column in spec.resolves}
    splits = {column: (yes, no) for column, yes, no in spec.splits}
    permitted = gold_permitted()
    for column in silver.columns:
        lines += [
            f"      - name: {column.name}",
            f"        data_type: {column.data_type}",
            "        description: " + _quote(column.description),
            "        config:",
            "          meta:",
            f"            classification: {column.classification}",
        ]
        if (silver.name, column.name) in permitted:
            lines.append(
                "            gold_generalisation: " + _quote(permitted[(silver.name, column.name)])
            )
        tests = []
        if column.name in resolves:
            to, to_column = resolves.pop(column.name)
            tests += [
                "          - silver_resolves_one_version:",
                "              arguments:",
                f"                to: ref('{to}')",
                f"                to_column: {to_column}",
                "                at: " + _quote(spec.instant),
                "              config:",
                "                severity: error",
            ]
        if column.name in splits:
            yes, no = splits.pop(column.name)
            tests += [
                "          - silver_flag_split:",
                "              arguments:",
                f"                minimum_true: {yes}",
                f"                minimum_false: {no}",
                "              config:",
                "                severity: error",
            ]
        if tests:
            lines += ["        data_tests:", *tests]
    if resolves or splits:
        unknown = sorted([*resolves, *splits])
        raise SystemExit(f"silver-generate: {silver.name} tests unknown columns {unknown}")
    return "\n".join(lines) + "\n"


def _consumers(text: str) -> dict[str, set[str]]:
    """Who reads each silver model: the planned models whose upstream names it, outside the
    generated section, and for a `ref` table the consumer the data dictionary's listing names."""
    head = text.split(BEGIN, 1)[0] + text.split(END, 1)[-1]
    out: dict[str, set[str]] = defaultdict(set)
    for line in head.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or not cells[0].startswith("`"):
            continue
        for name in re.findall(r"`(sl_[a-z_]+)`", cells[2]):
            out[name].add(cells[0])
    listing = DICTIONARY.read_text(encoding="utf-8").split(dbt_generate.REFERENCE_LISTING, 1)[-1]
    for line in listing.split("\n## ", 1)[0].splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].startswith("`") and cells[2] != "Consumed by":
            out[f"sl_{cells[0].strip('`')}"].add(cells[2])
    return out


def render_inventory(models: list[Silver], text: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit("silver-generate: docs/model_inventory.md has no silver markers")
    consumers = _consumers(text)
    generated = [m for m in models if m.spec.generated]
    rows = [
        "| Object | Grain | Upstream | Consumed by |",
        "|---|---|---|---|",
    ]
    for model in generated:
        if not consumers.get(model.name):
            raise SystemExit(
                f"silver-generate: {model.name} has no consumer in docs/model_inventory.md or "
                "the data dictionary's reference listing"
            )
        grain = "One row per version (SCD2): " + ", ".join(f"`{c}`" for c in model.grain)
        rows.append(
            f"| `{model.name}` | {grain} | `{model.bronze.name}` | "
            f"{'; '.join(sorted(consumers[model.name]))} |"
        )
    block = "\n".join(
        [
            BEGIN,
            "",
            f"{len(generated)} models generated from the contracts by `make silver-generate`: "
            "every `ref` table and `agent_locations`, each the entity historised and nothing "
            "more. An inactive `ref` row is retained as a version, current with `is_active` "
            "false.",
            "",
            *rows,
            "",
            END,
        ]
    )
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


def outputs() -> dict[Path, str]:
    models = build()
    files: dict[Path, str] = {}
    for model in models:
        files[MODELS / f"{model.name}.yml"] = render_yml(model)
        if model.spec.generated:
            files[MODELS / f"{model.name}.sql"] = render_sql(model)
    for feed in build_feeds():
        files[MODELS / f"{feed.feed.name}.yml"] = render_feed_yml(feed)
    files[INVENTORY] = render_inventory(models, INVENTORY.read_text(encoding="utf-8"))
    return files


def _generated_on_disk() -> set[Path]:
    """The silver files this generator wrote, recognised by their first line."""
    found = set()
    for path in MODELS.glob("sl_*.*"):
        first = path.read_text(encoding="utf-8").split("\n", 1)[0]
        if "Generated by scripts/silver_generate.py" in first:
            found.add(path)
    return found


def _shown(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)

    wanted = outputs()
    stale = sorted(_generated_on_disk() - set(wanted))
    if arguments.check:
        differing = [
            path
            for path, text in wanted.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        for path in differing + stale:
            print(f"silver-generate: {_shown(path)} differs from the contracts")
        if differing or stale:
            print("silver-generate: run `make silver-generate` and commit the result")
            return 1
        models = sum(1 for p in wanted if p.suffix == ".yml")
        sql = sum(1 for p in wanted if p.suffix == ".sql")
        print(
            f"silver-generate: {models} silver models' properties, {sql} generated models and "
            "the inventory agree with the contracts"
        )
        return 0

    MODELS.mkdir(parents=True, exist_ok=True)
    for path in stale:
        path.unlink()
    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8", newline="\n")
    print(f"silver-generate: wrote {len(wanted)} file(s), removed {len(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
