"""Generate the silver models that mirror a contract entity (specification 008 sections 2 and 5).

The contracts are the one source for what an entity carries, and `scripts/dbt_generate.py`
already reads them into the bronze models' columns, types, descriptions and classifications.
This builds on its `build_models()` and writes, for every silver model that mirrors one
relational entity:

- the model's properties, `dbt/models/silver/sl_<entity>.yml`: every column silver carries, with
  the bronze column's type, description and classification, the columns silver adds, its grain,
  its tests and its minimum cardinality; every silver model's contract is enforced
  (`dbt_project.yml`), so a model whose SQL returns anything else fails to build;
- for every `ref` table and for `agent_locations`, the model itself, `sl_<entity>.sql`, which is
  one call to the historisation macro: their silver is the contract's columns historised and
  nothing more, so writing them by hand would be thirty copies of one line;
- the generated section of the inventory's silver listing, between its markers.

A model with logic of its own, such as `sl_transactions`, which converts its amount, is written
by hand: this generates its properties and leaves its SQL alone, and the enforced contract holds
the two together.

`--check` regenerates everything in memory and fails on any difference, so a hand edit to a
generated file, or a contract changed without regenerating, fails in CI: the `dbt-generate`
pattern. Run it before `make dbt-generate`, whose bronze consumer lists read this section.

**What a mirroring model carries.** Its key, every contract column of its projection, the
version's `created_at` and `updated_at`, the `_batch_id` that read it, and for SCD2 the validity
columns. It does not carry `is_deleted`, which is false on every row silver keeps, the excluded
measures, which open no version and are wrong on every row but the one that opened it, or the
other audit columns, which describe a read rather than the entity.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "airflow" / "plugins"))

import dbt_generate  # noqa: E402
from data_contract import RELATIONAL  # noqa: E402

MODELS = ROOT / "dbt" / "models" / "silver"
INVENTORY = ROOT / "docs" / "model_inventory.md"
DICTIONARY = ROOT / "docs" / "data_dictionary.md"

BEGIN = "<!-- silver models: generated by scripts/silver_generate.py, do not edit by hand -->"
END = "<!-- end of generated silver models -->"

SCD2 = "scd2"
LATEST = "latest_state"

# The columns bronze carries for the platform, which silver does not mirror. `_batch_id` is
# carried, with its own meaning, and so are the two audit stamps.
NOT_MIRRORED = (
    "is_deleted",
    "_ingested_at",
    "_source_file",
    "_source_system",
    "_object_batch_id",
    "_object_ingest_date",
    "_raw_payload",
)
STAMPS = ("created_at", "updated_at", "_batch_id")

NON_PERSONAL = "non-personal"


@dataclass(frozen=True)
class Added:
    """A column silver adds to the entity's own."""

    name: str
    data_type: str
    description: str
    classification: str = NON_PERSONAL


@dataclass(frozen=True)
class Spec:
    """How one entity's silver model is built.

    `floor` is the model's minimum cardinality, a number stated here and never read from the
    data: for a `ref` table its seeded row count, for the rest a floor the `ci` book clears on its
    first day. `generated` models are one macro call; the rest are written by hand.
    """

    entity: str
    history: str
    floor: int
    excluded: tuple[str, ...] = ()
    added: tuple[Added, ...] = ()
    generated: bool = False
    deleted: str = "is_deleted"


SCD2_COLUMNS = (
    Added(
        "_valid_from",
        "TIMESTAMP WITH TIME ZONE",
        "When this version opens: the `updated_at` of the observation that opened it, except the "
        "key's first version, which opens at the epoch, 1900-01-01T00:00:00Z, because the first "
        "observed state is backdated as the earliest known state, not the true state.",
    ),
    Added(
        "_valid_to",
        "TIMESTAMP WITH TIME ZONE",
        "When this version closes, exclusive: the next version's opening, the instant a soft "
        "delete was recorded, or 9999-12-31T00:00:00Z while current. Never null.",
    ),
    Added(
        "_is_current",
        "BOOLEAN",
        "Whether this is the key's current version. A soft-deleted key has none.",
    ),
)

# The `ref` tables' seeded row counts at this commit, each a version at the epoch. A `ref` table
# with no floor here fails generation rather than going untested.
REFERENCE_FLOORS = {
    "account_statuses": 5,
    "account_types": 8,
    "card_product_classes": 5,
    "card_products": 7,
    "channels": 7,
    "countries": 30,
    "currencies": 9,
    "decision_reasons": 9,
    "entry_sides": 2,
    "fraud_dispositions": 5,
    "fraud_rules": 7,
    "gl_account_types": 5,
    "gl_accounts": 17,
    "gl_source_entities": 2,
    "holder_roles": 3,
    "interchange_rates": 210,
    "loan_application_statuses": 7,
    "loan_products": 6,
    "loan_statuses": 6,
    "login_outcomes": 5,
    "mcc_bands": 7,
    "mcc_codes": 22,
    "payment_schemes": 5,
    "payment_statuses": 7,
    "payment_types": 10,
    "regions": 6,
    "risk_bands": 5,
    "transaction_statuses": 6,
    "transaction_types": 18,
}

# Columns a reference model adds: the half-open business validity of interchange rates
# (specification 008 section 3).
BUSINESS_VALIDITY = (
    Added(
        "_business_valid_from_date",
        "DATE",
        "First day the row applies in business time: `valid_from_date`.",
    ),
    Added(
        "_business_valid_to_date",
        "DATE",
        "The day after the last day the row applies in business time, exclusive: "
        "`valid_to_date` plus one day, or 9999-12-31 while open. The source's last day is "
        "inclusive; silver exposes it half-open so a fact joins with `>=` and `<`.",
    ),
)
REFERENCE_ADDED = {"interchange_rates": BUSINESS_VALIDITY}

# Core banking entities whose silver is historisation alone, generated like the `ref` tables.
GENERATED_CORE = {"agent_locations": 3}

# Entities whose silver is written by hand; the properties are still generated from here.
HAND_WRITTEN: tuple[Spec, ...] = ()


def specs() -> list[Spec]:
    """Every silver model that mirrors a relational entity, in name order."""
    out = list(HAND_WRITTEN)
    for model in dbt_generate.build_models():
        if model.kind != RELATIONAL:
            continue
        schema = model.current.source_schema
        if schema == "ref":
            if model.entity not in REFERENCE_FLOORS:
                raise SystemExit(f"silver-generate: ref.{model.entity} has no floor")
            out.append(
                Spec(
                    model.entity,
                    SCD2,
                    REFERENCE_FLOORS[model.entity],
                    added=REFERENCE_ADDED.get(model.entity, ()),
                    generated=True,
                    deleted="false",
                )
            )
        elif model.entity in GENERATED_CORE:
            out.append(Spec(model.entity, SCD2, GENERATED_CORE[model.entity], generated=True))
    return sorted(out, key=lambda s: s.entity)


@dataclass
class Silver:
    spec: Spec
    bronze: dbt_generate.Model
    columns: list[dbt_generate.Column] = field(default_factory=list)

    @property
    def name(self) -> str:
        return f"sl_{self.spec.entity}"

    @property
    def key(self) -> list[str]:
        return list(self.bronze.current.keys)

    @property
    def grain(self) -> list[str]:
        return self.key + (["_valid_from"] if self.spec.history == SCD2 else [])


def _bronze_by_entity() -> dict[str, dbt_generate.Model]:
    return {m.entity: m for m in dbt_generate.build_models() if m.source_system == "corebank"}


def _stamp(name: str, history: str, bronze: dbt_generate.Column) -> dbt_generate.Column:
    if name == "_batch_id":
        opened = "opened this version" if history == SCD2 else "is the entity's latest"
        return dbt_generate.Column(
            name,
            bronze.data_type,
            NON_PERSONAL,
            f"The earliest batch that read the observation which {opened}: re-reads of one "
            "version collapse to it. Classification: `non-personal` (no restriction).",
        )
    whose = "the observation that opened this version"
    if history != SCD2:
        whose = "the latest observation"
    return dbt_generate.Column(
        name,
        bronze.data_type,
        bronze.classification,
        f"{bronze.description} In silver, the value of {whose}.",
    )


def build() -> list[Silver]:
    bronze = _bronze_by_entity()
    out = []
    for spec in specs():
        source = bronze[spec.entity]
        silver = Silver(spec, source)
        by_name = {c.name: c for c in source.columns}
        for name in spec.excluded:
            if name not in by_name:
                raise SystemExit(f"silver-generate: {spec.entity}.{name} is not a contract column")
        skipped = set(NOT_MIRRORED) | set(STAMPS) | set(spec.excluded)
        ordered = silver.key + [c.name for c in source.columns if c.name not in silver.key]
        for name in ordered:
            if name in skipped:
                continue
            silver.columns.append(by_name[name])
        for name in STAMPS:
            silver.columns.append(_stamp(name, spec.history, by_name[name]))
        added = (SCD2_COLUMNS if spec.history == SCD2 else ()) + spec.added
        for column in added:
            silver.columns.append(
                dbt_generate.Column(
                    column.name,
                    column.data_type,
                    column.classification,
                    f"{column.description} Classification: `{column.classification}` "
                    f"({dbt_generate.CLASS_NOTE[column.classification]}).",
                )
            )
        names = [c.name for c in silver.columns]
        if len(names) != len(set(names)):
            raise SystemExit(f"silver-generate: {silver.name} declares a column twice")
        out.append(silver)
    return out


# --- rendering --------------------------------------------------------------------------------

_quote = dbt_generate._quote


def render_sql(silver: Silver) -> str:
    spec = silver.spec
    key = ", ".join(f"'{k}'" for k in silver.key)
    call = f"{spec.history}(ref('{silver.bronze.name}'), [{key}]"
    if spec.excluded:
        call += ", excluded=[" + ", ".join(f"'{e}'" for e in spec.excluded) + "]"
    if spec.deleted != "is_deleted":
        call += f", deleted='{spec.deleted}'"
    call += ")"
    header = (
        f"-- Generated by scripts/silver_generate.py from {silver.bronze.contract_path}; "
        "do not edit.\n"
    )
    if not any(a in BUSINESS_VALIDITY for a in spec.added):
        return header + f"{{{{ {call} }}}}\n"
    return (
        header
        + "select\n"
        + "    *,\n"
        + "    valid_from_date as _business_valid_from_date,\n"
        + "    {{ business_valid_to('valid_to_date') }} as _business_valid_to_date\n"
        + f"from (\n    {{{{ {call} }}}}\n)\n"
    )


def _describe_model(silver: Silver) -> str:
    spec = silver.spec
    grain = ", ".join(f"`{c}`" for c in silver.grain)
    if spec.history == SCD2:
        kind = (
            "One row per version (SCD2): a version opens when a projection column changes, or "
            "when no contract column changed at all"
        )
        if spec.excluded:
            kind += "; a change confined to " + ", ".join(f"`{e}`" for e in spec.excluded)
            kind += " opens none, and it is not carried"
        kind += "."
    else:
        kind = "One row per entity, its latest observation; a soft-deleted entity is absent."
    if spec.deleted == "false":
        deleted = " An inactive row is retained as a version, current with `is_active` false."
    elif spec.history == SCD2:
        deleted = " A soft delete closes the final version and leaves no current one."
    else:
        deleted = ""
    return (
        f"Silver {spec.entity}, from `{silver.bronze.name}` ({silver.bronze.contract_path}). "
        f"{kind}{deleted} Re-reads of one version collapse to the earliest batch. "
        f"Grain: {grain}."
    )


def render_yml(silver: Silver) -> str:
    spec = silver.spec
    grain = ", ".join(silver.grain)
    key = ", ".join(silver.key)
    lines = [
        "# Generated by scripts/silver_generate.py from the contracts; do not edit.",
        "version: 2",
        "models:",
        f"  - name: {silver.name}",
        "    description: " + _quote(_describe_model(silver)),
        "    config:",
        "      meta:",
        f"        entity: {spec.entity}",
        f"        history: {spec.history}",
        f"        upstream: {silver.bronze.name}",
        f"        grain: [{grain}]",
        f"        excluded: [{', '.join(spec.excluded)}]",
        f"        generated_sql: {'true' if spec.generated else 'false'}",
        "    data_tests:",
        "      - silver_unique_key:",
        "          arguments:",
        f"            columns: [{grain}]",
        "          config:",
        "            severity: error",
        "      - silver_not_null:",
        "          arguments:",
        f"            columns: [{grain}]",
        "          config:",
        "            severity: error",
        "      - silver_min_rows:",
        "          arguments:",
        f"            minimum: {spec.floor}",
        "          config:",
        "            severity: error",
        "      - silver_rereads_agree:",
        "          arguments:",
        f"            upstream: ref('{silver.bronze.name}')",
        f"            key: [{key}]",
        "          config:",
        "            severity: error",
    ]
    if spec.history == SCD2:
        lines += [
            "      - silver_scd2_intervals:",
            "          arguments:",
            f"            key: [{key}]",
            "          config:",
            "            severity: error",
        ]
    lines.append("    columns:")
    for column in silver.columns:
        lines += [
            f"      - name: {column.name}",
            f"        data_type: {column.data_type}",
            "        description: " + _quote(column.description),
            "        config:",
            "          meta:",
            f"            classification: {column.classification}",
        ]
    return "\n".join(lines) + "\n"


def _consumers(text: str) -> dict[str, set[str]]:
    """Who reads each silver model: the planned models whose upstream names it, outside the
    generated section, and for a `ref` table the consumer the data dictionary's listing names."""
    head = text.split(BEGIN, 1)[0] + text.split(END, 1)[-1]
    out: dict[str, set[str]] = defaultdict(set)
    for line in head.splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3 or not cells[0].startswith("`"):
            continue
        for name in re.findall(r"`(sl_[a-z_]+)`", cells[2]):
            out[name].add(cells[0])
    listing = DICTIONARY.read_text(encoding="utf-8").split(dbt_generate.REFERENCE_LISTING, 1)[-1]
    for line in listing.split("\n## ", 1)[0].splitlines():
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and cells[0].startswith("`") and cells[2] != "Consumed by":
            out[f"sl_{cells[0].strip('`')}"].add(cells[2])
    return out


def render_inventory(models: list[Silver], text: str) -> str:
    if BEGIN not in text or END not in text:
        raise SystemExit("silver-generate: docs/model_inventory.md has no silver markers")
    consumers = _consumers(text)
    generated = [m for m in models if m.spec.generated]
    rows = [
        "| Object | Grain | Upstream | Consumed by |",
        "|---|---|---|---|",
    ]
    for model in generated:
        if not consumers.get(model.name):
            raise SystemExit(
                f"silver-generate: {model.name} has no consumer in docs/model_inventory.md or "
                "the data dictionary's reference listing"
            )
        grain = "One row per version (SCD2): " + ", ".join(f"`{c}`" for c in model.grain)
        rows.append(
            f"| `{model.name}` | {grain} | `{model.bronze.name}` | "
            f"{'; '.join(sorted(consumers[model.name]))} |"
        )
    block = "\n".join(
        [
            BEGIN,
            "",
            f"{len(generated)} models generated from the contracts by `make silver-generate`: "
            "every `ref` table and `agent_locations`, each the entity historised and nothing "
            "more. An inactive `ref` row is retained as a version, current with `is_active` "
            "false.",
            "",
            *rows,
            "",
            END,
        ]
    )
    head, rest = text.split(BEGIN, 1)
    _, tail = rest.split(END, 1)
    return head + block + tail


def outputs() -> dict[Path, str]:
    models = build()
    files: dict[Path, str] = {}
    for model in models:
        files[MODELS / f"{model.name}.yml"] = render_yml(model)
        if model.spec.generated:
            files[MODELS / f"{model.name}.sql"] = render_sql(model)
    files[INVENTORY] = render_inventory(models, INVENTORY.read_text(encoding="utf-8"))
    return files


def _generated_on_disk() -> set[Path]:
    """The silver files this generator wrote, recognised by their first line."""
    found = set()
    for path in MODELS.glob("sl_*.*"):
        first = path.read_text(encoding="utf-8").split("\n", 1)[0]
        if "Generated by scripts/silver_generate.py" in first:
            found.add(path)
    return found


def _shown(path: Path) -> str:
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)

    wanted = outputs()
    stale = sorted(_generated_on_disk() - set(wanted))
    if arguments.check:
        differing = [
            path
            for path, text in wanted.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        for path in differing + stale:
            print(f"silver-generate: {_shown(path)} differs from the contracts")
        if differing or stale:
            print("silver-generate: run `make silver-generate` and commit the result")
            return 1
        models = sum(1 for p in wanted if p.suffix == ".yml")
        sql = sum(1 for p in wanted if p.suffix == ".sql")
        print(
            f"silver-generate: {models} silver models' properties, {sql} generated models and "
            "the inventory agree with the contracts"
        )
        return 0

    MODELS.mkdir(parents=True, exist_ok=True)
    for path in stale:
        path.unlink()
    for path, text in wanted.items():
        path.write_text(text, encoding="utf-8", newline="\n")
    print(f"silver-generate: wrote {len(wanted)} file(s), removed {len(stale)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
